name: Download Kaggle Dataset

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight. Adjust as needed.
  workflow_dispatch: # Allows you to run it manually

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Kaggle CLI
        run: pip install kaggle

      - name: Download Dataset
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |
          # Replace 'user/dataset-name' with the actual dataset slug
          kaggle datasets download -d jockeroika/atp-tennis-dataset-2000-2025 --unzip -p ./data

      - name: Commit and Push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/
          git commit -m "Update dataset: $(date +'%Y-%m-%d')" || exit 0
          git push